### ISSUE TITLE
Review 1: Menampilkan data bulan dan tahun

### ISSUE THREAD

**Issue by priyandari** [igochaniago/Kelompok2-KelasC#7]
Saran saya tambahkan daftar file yang telah dikelola

**Comment by igochaniago** [comment]
Untuk issue ini sudah kami perbaiki, silahkan dapat di review kembali Pak. Sudah kami tambahkan dalam Program dan juga sebagai tambahan lain kami juga meng-update Readme.txt yang berisi tatacara menjalankan program
