### ISSUE TITLE
Review 1: Perbedaan program dengan program awal

### ISSUE THREAD

**Issue by priyandari** [igochaniago/Kelompok2-KelasC#8]
Berikan informasi apa perbedaan program yang dibuat dengan program yang menjadi sumber inspirasi

**Comment by priyandari** [comment]
Sampaikan pada bagian readme, dan tuliskan pada bagian readme link menuju program sumber inspirasi

**Comment by igochaniago** [comment]
Untuk issue ini sudah kami perbaiki, silahkan dapat di review kembali Pak. Sudah kami tambahkan di Readme.txt dalam folder Referensi-Program
