### ISSUE TITLE
Bug: Mistype

### ISSUE THREAD

**Issue by priyandari** [igochaniago/Kelompok2-KelasC#9]
masih perlu penagangan error handling. contoh tampa sengaja input t pada bulan (harusnya angka)..

**Comment by igochaniago** [comment]
Untuk issue ini sudah kami perbaiki, silahkan dapat di review kembali Pak. Kami tambahkan function try dan except pada definisi inputpembukuan() dan cekpembukuan(). Dan untuk error handling yang dimaksud adalah pada ValueError sehingga kami tambahkan except ValueError.
